# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: COMPILADOR AUTOMATICO

on:
  schedule:
    - cron: '0 14 * * *'
  push:
    
  # workflow_dispatch serve para poder rodar o action manualmente também
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'
    - name: Run Project
      run: |
            chmod +x runner.sh
            ./runner.sh
    
    
