# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: COMPILADOR AUTOMATICO

on:
  schedule:
    - cron: '0 14 * * *'
  push:
  pull_request:
    
  # workflow_dispatch serve para poder rodar o action manualmente também
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'
    - name: Compile files
      run: |
            cd Filas
            javac Random.java Evento.java Fila.java Escalonador.java Algoritmo.java Main.java
    - name: Run Project
      run: |
            java Main
            java Main >> resultado.txt
    
    # Avisando que as infos foram salvas
    - name: Adicionando que foi confirmado
      run: echo "✔️ Workflow rodado com sucesso dia $(date +"%d/%m/%Y")!" >> datas_backup.txt
          
      # Criando um commit
    - name: Criando um commit
      run: |
          git status
          git config user.email "${{secrets.EMAIL}}"
          git config user.name "${{secrets.USER_NAME}}"
          git add resultado.txt
          git commit -m "✔️ Testado e funcionando o simulador de filas"
      
    # Fazendo push pelo actions
    - uses: ad-m/github-push-action@master
      with:
          github_token: ${{secrets.TOKEN}}
          force: true
